# basic info
title: Yiran Zhao @ NUS
name: Yiran Zhao
logo: /assets/img/my_pic.jpg
description: Ph.D. Candidate at NUS
location: xxxx
email: zhayiran[at]u[dot]nus[dot]edu
linkedin: yiran-zhao-423950222
google_scholar: D_HwSlEAAAAJ
# Others 
show_downloads: false 
# google_analytics: UA-235425498-1
theme: jekyll-theme-minimal
